version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: proyecto-gestion-backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=your_database_name
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: